CREATE TABLE PETINF(
 PETID                 int NOT NULL,
 PETNAME               VARCHAR(14),
 PETTYPE               VARCHAR(13),
 PETAGE                 int NOT NULL,
PETOWNER		VARCHAR(14),
CONSTRAINT PETINF_PRIMARY_KEY PRIMARY KEY (PETID));

INSERT INTO PETINF VALUES (1,'DOG','MALE',13,'kavi');
INSERT INTO PETINF VALUES (2,'RABBIT','MALE',16,'SAI');
INSERT INTO PETINF VALUES (3,'CAT','MALE',17,'babu');
INSERT INTO PETINF VALUES (4,'SANKE','MALE',31,'NANI');
INSERT INTO PETINF VALUES (5,'RAT','MALE',18,'Srav');
INSERT INTO PETINF VALUES (6,'PARROT','FEMALE',25,'deepa');

SELECT * FROM PETINF;